# Generated by Django 4.2.6 on 2023-10-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participacao',
            new_name='Participante',
        ),
    ]
